### ISSUE TITLE
mutual_inf_cd_2d() function returns a single value instead of a vector

### ISSUE THREAD

**Issue by katgit** [montilab/knnmi#1]
mutual_inf_cd_2d() function returns a single value instead of a vector:

```
set.seed(42)
x <- runif(10, min=0, max=1)
M = matrix(rep(c(2,2,0,2,1,1,1,0,1,1), 3), ncol=3)
mutual_inf_cd_2d(x, M, k=3)
## [1] 0.1115698
```

**Comment by bu-bgregor** [comment]
Katia - in the knn_mi.c code I get the dimensions of the matrix M with:

```
    y_ncols = Rf_ncols(r_input_y);
    y_nrows = Rf_nrows(r_input_y);
```

Instead of the expected y_ncols=3 and y_nrows=10 I get:   y_ncols=1 and y_nrows=30.  If I add check to see if it's a matrix:
`    printf("IS_MATRIX %d\n", Rf_isMatrix(r_input_y));`
that prints 0.  Any suggestions?

**Comment by katgit** [comment]
Brian, you can take a look how I do it in CaDrA package:
https://github.com/montilab/CaDrA/blob/master/src/score_fun.c (see ks_genescore_mat_ function)

**Comment by bu-bgregor** [comment]
I think I found it. In the R wrapper there's a conversion to an integer matrix:

```
mutual_inf_cd_2d <- function(x, M, k=3L, use_cc=FALSE){

  stopifnot( "x and M must have the same length"=length(x) == nrow(M) )
  res <- .Call('_mutual_inf_cd_2d', x, **as.integer(M)**,
               as.integer(k), as.logical(use_cc))
  res
}
```
and that made an integer vector, not a 2D matrix.  Changing it like this:
```
mutual_inf_cd_2d <- function(x, M, k=3L, use_cc=FALSE){
  stopifnot( "x and M must have the same length"=length(x) == nrow(M) )
  if (!is.integer(M)) {
    M <- matrix(as.integer(M), nrow=nrow(M))
  }
  res <- .Call('_mutual_inf_cd_2d', x, M,
               as.integer(k), as.logical(use_cc))
  res
}
```
fixes the issue.
